module.exports = function authSchema(postgres = false) {
  const id = postgres ? 'BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY' : 'INTEGER PRIMARY KEY AUTOINCREMENT';
  return [
    `CREATE TABLE IF NOT EXISTS users (
      id ${id}, name TEXT NOT NULL, email TEXT NOT NULL UNIQUE,
      password_hash TEXT NOT NULL,
      role TEXT NOT NULL DEFAULT 'customer' CHECK (role IN ('customer', 'admin')),
      created_at TEXT NOT NULL
    )`,
    `CREATE TABLE IF NOT EXISTS sessions (
      token_hash TEXT PRIMARY KEY,
      user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
      expires_at BIGINT NOT NULL
    )`,
    'CREATE INDEX IF NOT EXISTS sessions_expiry ON sessions(expires_at)',
    `CREATE TABLE IF NOT EXISTS auth_limits (
      key TEXT PRIMARY KEY, hits INTEGER NOT NULL, expires_at BIGINT NOT NULL
    )`,
  ];
};
