const { neon } = require('@neondatabase/serverless');
const products = require('./seed');

module.exports = function createPostgres(connectionString) {
  const sql = neon(connectionString);
  let initialization;

  function initialize() {
    if (!initialization) {
      initialization = sql.transaction([
        // Serializa a inicialização entre instâncias; liberado no commit/rollback.
        sql.query('SELECT pg_advisory_xact_lock(734821, 1)'),
        sql.query(`
          CREATE TABLE IF NOT EXISTS products (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            name TEXT NOT NULL,
            description TEXT NOT NULL,
            price DOUBLE PRECISION NOT NULL,
            stock BIGINT NOT NULL,
            category TEXT NOT NULL
          )
        `),
        sql.query(`
          INSERT INTO products (name, description, price, stock, category)
          SELECT name, description, price, stock, category
          FROM jsonb_to_recordset($1::jsonb)
            AS seed(name TEXT, description TEXT, price DOUBLE PRECISION, stock BIGINT, category TEXT)
          WHERE NOT EXISTS (SELECT 1 FROM products)
        `, [JSON.stringify(products)]),
        ...require('./auth-schema')(true).map(statement => sql.query(statement)),
      ], { isolationLevel: 'ReadCommitted' }).catch(error => {
        initialization = undefined;
        throw error;
      });
    }
    return initialization;
  }

  return {
    async query(statement, parameters = []) {
      await initialize();
      // Somente SQL fixo do repositório usa '?'; valores seguem separados.
      let position = 0;
      const text = statement.replace(/\?/g, () => `$${++position}`);
      const rows = await sql.query(text, parameters);
      // BIGINT chega como string; preserve o contrato numérico da API.
      return rows.map(row => {
        const result = { ...row };
        for (const field of ['id', 'price', 'stock', 'user_id', 'expires_at', 'hits']) {
          if (result[field] !== undefined && result[field] !== null) result[field] = Number(result[field]);
        }
        return result;
      });
    },
  };
};
